major_event_log/urls.py
"""Define the URLs that are part of the app as regex patterns.

Each regex pattern will map to a page of the application and
load the corresponding view.
"""
from django.urls import path

from . import views
from . import feeds


urlpatterns = [
    # Matches root index of app ('/').
    path('', views.EventList.as_view(), name='index'),
    # Matches urls like 'event/123a-4b56c-78d.premis.xml'.
    path('event/<slug:event_id>.premis.xml',
         views.event_premis, name='event_premis'),
    # Matches URLs like 'event/123a-4b56c-78d.xml'.
    path('event/<slug:event_id>.xml', views.event_atom,
         name='event_atom'),
    # Matches URLs like 'event/123a-4b56c-78d/'.
    path('event/<slug:event_id>/', views.event_details,
         name='event_details'),
    # Matches 'feed/'.
    path('feed/', feeds.LatestEventsFeed(), name='feed'),
    # Matches 'about/'.
    path('about/', views.about, name='about'),
]

major_event_log/models.py
"""Model definition.

The Event class defines all the data required in order to create a
major PREMIS event.
"""
import uuid

from django.db import models
from django.urls import reverse


class Event(models.Model):
    SUCCESS = 'http://purl.org/NET/UNTL/vocabularies/eventOutcomes/#success'
    FAILURE = 'http://purl.org/NET/UNTL/vocabularies/eventOutcomes/#failure'
    OUTCOME_CHOICES = (
        (SUCCESS, 'Success'),
        (FAILURE, 'Failure'),
    )
    # Unique identifier for each event. Primary key.
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    detail = models.TextField()
    outcome = models.CharField(max_length=80, choices=OUTCOME_CHOICES)
    outcome_detail = models.TextField()
    # Date of the event, NOT the date of entry.
    date = models.DateTimeField()
    entry_created = models.DateTimeField(auto_now_add=True)
    entry_modified = models.DateTimeField(auto_now=True)
    # The contact_name attribute will be used as the reporting agent.
    contact_name = models.CharField(max_length=100,
                                    help_text='Appears as the Reporting Agent')
    contact_email = models.EmailField()

    def get_absolute_url(self):
        return reverse('major-event-log:event_details', args=[self.id])

    def is_success(self):
        return self.outcome == self.SUCCESS

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title

major_event_log/views.py
"""Defines all the views, which load the requested pages.

These views will render the appropriate web pages based on
templates defined in the 'templates/major-event-log' directory.
"""
import uuid

from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import ListView

from .models import Event


def get_event_or_404(event_id):
    """Retrieves event, if possible. If not, raises HTTP 404 response.

    Checks two separate things related to the given event_id. The first
    is that the event_id is a well-formed UUID. If the event_id is a
    valid UUID, then the get_object_or_404 function is called to check
    that the valid UUID actually refers to an event that has already
    been created in the db. If either of these checks fail, then an
    HTTP 404 response is sent.
    """
    try:
        uuid.UUID(event_id)
    except ValueError:
        raise Http404('Invalid event ID')
    return get_object_or_404(Event.objects, id=event_id)


class EventList(ListView):
    template_name = 'major-event-log/index.html'
    queryset = Event.objects.order_by('-entry_created')
    context_object_name = 'events'
    paginate_by = 10


def event_details(request, event_id):
    """Loads the event details page of the event with the given ID."""
    event = get_event_or_404(event_id)
    context = {'event': event}
    return render(request, 'major-event-log/event_details.html', context)


def event_atom(request, event_id):
    """Loads the Atom record for the event with the given ID."""
    event = get_event_or_404(event_id)
    event_detail_url = request.build_absolute_uri(event.get_absolute_url())
    context = {'event': event, 'event_details_url': event_detail_url}
    return render(request, 'major-event-log/event_atom.xml', context,
                  content_type='text/xml; charset=utf-8')


def event_premis(request, event_id):
    """Loads the PREMIS event item for the event with the given ID."""
    event = get_event_or_404(event_id)
    context = {'event': event}
    return render(request, 'major-event-log/event_premis.xml', context,
                  content_type='text/xml; charset=utf-8')


def about(request):
    """Loads the 'about' page."""
    return render(request, 'major-event-log/about.html')

major_event_log/templates/major-event-log/about.html
{% extends 'major-event-log/base.html' %}

{% block title %}About{% endblock %}

{% block content %}

	<div class='page-header'>
		<h1>About</h1>
	</div>
    <p>This application serves to document major events related to the UNT Libraries` digital preservation projects. These events are not tied to specific objects, but rather affect all preserved objects or major subsets of objects.</p>
    <p>The events themselves can be viewed collectively on the home page or individually by clicking on the appropriate event's ID, which will take you to the details page. This page can present the details in HTML, PREMIS XML, or the Atom format. Additionally, the Atom feed shows 10 events per page, ordered by creation date, newest first.</p>

{% endblock %}

major_event_log/templates/major-event-log/base.html
<!DOCTYPE html>
<html lang='en'>
	<head>
	<title>{% block title %}{% endblock %}</title>
		<meta charset='utf-8'>
		<meta name='viewport' content='width=device-width, initial-scale=1'>
		<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.4/yeti/bootstrap.min.css'>
		<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
		<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>
	</head>
	<body>
        {% include 'major-event-log/navbar.html' %}
		<div class="container">
			{% block content %}{% endblock %}	
		</div>
	</body>
</html>

major_event_log/templates/major-event-log/button_grp_bottom.html
<div class='container text-left'>
	<div class='btn-group'>
		<a href={% url 'major-event-log:event_atom' event.id %} class='btn btn-primary'>Atom</a>
		<a href={% url 'major-event-log:event_premis' event.id %} class='btn btn-primary'>PREMIS</a>
	</div>
</div>

major_event_log/templates/major-event-log/event_detail.html
{% extends "major-event-log/base.html" %}

{% block title %}Event Details{% endblock %}

{% block content %}
	<div class="page-header">
		<h1>Details for {{ event.id }}</h1>
	</div>
	<table class="table table-striped">
		<tr>
			<th><b>Title</b></th>
			<td>{{ event.title }}</td>
		</tr>
		<tr>
			<th><b>Details</b></th>
			<td>{{ event.detail }}</td>
		</tr>
		<tr>
			<th><b>ID</b></th>
			<td>{{ event.id }}</td>
		</tr>
		<tr>
			<th><b>Outcome</b></th>
		{% if event.get_outcome_display == 'Success' %}
			<td><span class="label label-success">{{ event.get_outcome_display }}</span></td>
		{% else %}
			<td><span class="label label-danger">{{ event.get_outcome_display }}</span></td>
		{% endif %}
		</tr>
		<tr>
			<th><b>Outcome Details</b></th>
			<td>{{ event.outcome_detail }}</td>
		</tr>
		<tr>
			<th><b>Event Date</b></th>
			<td>{{ event.date }}</td>
		</tr>
		<tr>
			<th><b>Created</b></th>
			<td>{{ event.entry_created }}</td>
		</tr>
		<tr>
			<th><b>Modified</b></th>
			<td>{{ event.entry_modified }}</td>
		</tr>
		<tr>
			<th><b>Contact Name</b></th>
			<td>{{ event.contact_name }}</td>
		</tr>
		<tr>
			<th><b>Contact Email</b></th>
			<td>{{ event.contact_email }}</td>
		</tr>
	</table>
	{% include "major-event-log/button_grp_bottom.html" %}
{% endblock %}

major_event_log/templates/major-event-log/event_details.html
{% extends 'major-event-log/base.html' %}

{% block title %}Event Details{% endblock %}

{% block content %}
    <h2>Event Details</h2>
	<table class='table table-striped'>
		<tr>
			<th><b>Title</b></th>
			<td>{{ event.title }}</td>
		</tr>
		<tr>
			<th><b>Details</b></th>
			<td>{{ event.detail }}</td>
		</tr>
		<tr>
			<th><b>ID</b></th>
			<td><samp>{{ event.id }}</samp></td>
		</tr>
		<tr>
			<th><b>Outcome</b></th>
            <td><span class='label label-{% if event.is_success %}success{% else %}danger{% endif %}'><samp>{{ event.get_outcome_display }}</samp></span></td>
		</tr>
		<tr>
			<th><b>Outcome Details</b></th>
			<td>{{ event.outcome_detail }}</td>
		</tr>
		<tr>
			<th><b>Event Date</b></th>
			<td>{{ event.date }}</td>
		</tr>
    </table>
    <h2>Event Metadata</h2>
	<table class='table table-striped'>
		<tr>
			<th><b>Created</b></th>
			<td>{{ event.entry_created }}</td>
		</tr>
		<tr>
			<th><b>Modified</b></th>
			<td>{{ event.entry_modified }}</td>
		</tr>
		<tr>
			<th><b>Contact Name</b></th>
			<td>{{ event.contact_name }}</td>
		</tr>
		<tr>
			<th><b>Contact Email</b></th>
			<td>{{ event.contact_email }}</td>
		</tr>
	</table>
	{% include 'major-event-log/button_grp_bottom.html' %}
{% endblock %}

major_event_log/templates/major-event-log/index.html
{% extends 'major-event-log/base.html' %}

{% block title %}Major Event Log{% endblock %}

{% block content %}
	<div class='page-header'>
		<h1>Major Event Log</h1>
	</div>
    {% if events %}
        <table class='table table-striped table-hover'>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Event Date</th>
                    <th>Event</th>
                    <th>Outcome</th>
                </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td><a href='{% url "major-event-log:event_details" event.id %}'><samp>{{ event.id }}</samp></a></td>
                    <td>{{ event.date|date:"N d, Y" }}</td>
                    <td>{{ event.title }}</td>
                    <td><span class='label label-{% if event.is_success %}success{% else %}danger{% endif %}'><samp>{{ event.get_outcome_display }}</samp></span></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            {% include 'major-event-log/pagination.html' %}
        {% endif %}
    {% else %}
        <h2>No events have been created.</h2>
    {% endif %}
{% endblock %}

major_event_log/templates/major-event-log/navbar.html
<nav class='navbar navbar-inverse'>
    <div class='container-fluid'>
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#Navbar'>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
            <a class='navbar-brand' href='{% url "major-event-log:index" %}'><span class='glyphicon glyphicon-home'></span> Major Event Log</a>
        </div>
        <div class='collapse navbar-collapse' id='Navbar'>
            <ul class='nav navbar-nav navbar-right'>
                <li><a href='{% url "major-event-log:about" %}'>About</a></li>
                <li><a href='{% url "major-event-log:feed" %}'>Atom Feed</a></li>
            </ul>
        </div>
    </div>
</nav>

major_event_log/templates/major-event-log/pagination.html
<nav>
    <ul class='pagination'>
        {% if page_obj.number == 1 %}
        <li class='disabled'><span>First</span></li>
        {% else %}
        <li><a href='?page=1'>First</a></li>
        {% endif %}

        {% if page_obj.has_previous %}
        <li><a href='?page={{ page_obj.previous_page_number }}'>Previous</a></li>
        {% else %}
        <li class='disabled'><span>Previous</span></li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
            <li class='active'><span>{{ page }}</span></li>
            {% else %}
            <li><a href='?page={{ page}}'>{{ page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li><a href='?page={{ page_obj.next_page_number }}'>Next</a></li>
        {% else %}
        <li class='disabled'><span>Next</span></li>
        {% endif %}

        {% if page_obj.number == page_obj.paginator.num_pages %}
        <li class='disabled'><span>Last</span></li>
        {% else %}
        <li><a href='?page={{ page_obj.paginator.num_pages }}'>Last</a></li>
        {% endif %}
    </ul>
</nav>